name: Build and test GO
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up GO 1.14
        uses: actions/setup-go@v2
        with:
          go-version: "^1.14.0"

      - name: Check out source code
        uses: actions/checkout@v2
        env:
          GOPROXY: "https://proxy.golang.org"

      - uses: extractions/netrc@v1
        with:
          machine: github.com
          username: ${{ github.actor }}
          password: ${{ secrets.ACTIONS_PAT }}

      - name: Download GO modules
        env:
          GOPROXY: "https://proxy.golang.org"
        run: go mod vendor

      - name: Test
        env:
          GOPROXY: "https://proxy.golang.org"
        run: make go-test

      - name: Build
        env:
          GOPROXY: "https://proxy.golang.org"
        run: make go-build
