name: test and build GO
on: [push, pull_request]
jobs:
  run-go:
    name: Lint, Test and Build Go
    runs-on: ubuntu-latest
    steps:
      - name: Set up GO 1.14
        uses: actions/setup-go@v2
        with:
          go-version: "^1.14.0"

      - name: Check out source code
        uses: actions/checkout@v2
        env:
          GOPROXY: "https://proxy.golang.org"

      - uses: extractions/netrc@v1
        with:
          machine: github.com
          username: ${{ github.actor }}
          password: ${{ secrets.ACTIONS_PAT }}

      - name: Download GO modules
        env:
          GOPROXY: "https://proxy.golang.org"
        run: go mod vendor

      - name: Lint
        uses: actions-contrib/golangci-lint@v1
        env:
          GOROOT: ""
          GO111MODULE: on
          GOPROXY: "https://proxy.golang.org"
        with:
          args: "run ./... "

      - name: Test
        env:
          GOPROXY: "https://proxy.golang.org"
        run: make go-test

      - name: Build
        env:
          GOPROXY: "https://proxy.golang.org"
        run: make go-build app_env=development app_port=8080

  run-docker:
    needs: run-go
    name: Lint, Build  and Push Docker
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@master
      - name: lint
        uses: burdzwastaken/hadolint-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HADOLINT_ACTION_DOCKERFILE_FOLDER: .
      - name: build and push
        uses: docker/build-push-action@v1
        with:
          build_args: app_env=development,app_port=8080
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: nofsky/web-app-development
          tags: latest




